### PR TITLE
Add favicon to "default" templates; handle /robots.txt; use relative redirects (for use behind proxies or in Docker containers)

### PR DESCRIPTION
**Pull request by cmanley**
Relative redirects (without scheme://host:port part) are allowed as part of RFC 7231 and make it much easier to use viewvc in a container or behind a proxy:
https://stackoverflow.com/questions/8250259/is-a-302-redirect-to-relative-url-valid-or-invalid
Those are the changes necessary to run viewvc standalone in a Docker container:
https://github.com/cmanley/viewvc-docker/tree/debian-standalone-dev

### CODE REVIEW

**Comment by aik099** [comment]
Ran into both issues fixed here independently while packaging ViewVC 1.3.0 for a Docker deployment (nginx + fcgiwrap, not `bin/standalone.py`, so a different code path than this PR touches, but the same underlying problems):

- **Missing favicon in the `default` template** — confirmed still true in 1.3.0. `templates/classic/docroot/images/favicon.ico` and its `<link rel="shortcut icon">` header tag exist, but `templates/default/` has neither the file nor the reference. I ended up copying the icon over from `classic` and patching it into `templates/default/_header.ezt` at build time as a workaround.
- **Absolute redirects breaking behind a proxy/in a container** — also still present. My nginx config's `/` → `/cgi-bin/viewvc.cgi` redirect dropped the port on non-default ports until I forced it to build the Location header from `$http_host` explicitly, for the same underlying reason `@cmanley` describes here (container/proxy port mapping getting lost when the app infers its own host:port).

@cmpilato — since this predates a maintainer review and was closed without comment back in 2020, is it worth reviving a version of this scoped to the CGI/WSGI paths (not just `standalone.py`)? Happy to help split it into smaller focused patches (favicon separately from the redirect/robots.txt changes) if that would make it easier to review than the original combined PR.

**Comment by cmpilato** [comment]
Hrm. Weird that I would close this issue without comment.

> * **Missing favicon in the `default` template** — confirmed still true in 1.3.0. `templates/classic/docroot/images/favicon.ico` and its `<link rel="shortcut icon">` header tag exist, but `templates/default/` has neither the file nor the reference. I ended up copying the icon over from `classic` and patching it into `templates/default/_header.ezt` at build time as a workaround.

Yeah, this was an old oversight.  I've made the tweaks on `master` and backported to `1.3.x`.

> * **Absolute redirects breaking behind a proxy/in a container** — also still present. My nginx config's `/` → `/cgi-bin/viewvc.cgi` redirect dropped the port on non-default ports until I forced it to build the Location header from `$http_host` explicitly, for the same underlying reason `@cmanley` describes here (container/proxy port mapping getting lost when the app infers its own host:port).
> 
> @cmpilato — since this predates a maintainer review and was closed without comment back in 2020, is it worth reviving a version of this scoped to the CGI/WSGI paths (not just `standalone.py`)? Happy to help split it into smaller focused patches (favicon separately from the redirect/robots.txt changes) if that would make it easier to review than the original combined PR.

I do think it would be good to have separate changes for the redirect bits and robots.txt as I don't immediately see the technical connection between the two.  It's worth considering that either (or both) of these behaviors might need to be behind a configuration option, too, but I honestly haven't thought enough about it to say for sure.  (I have essentially zero faith that the more irresponsible actors even honor the robots.txt file, but I guess that's another matter...)

**Comment by aik099** [comment]
@cmpilato, created #411 PR with port lost on redirect changes only. Ready for review.

Nowadays, with AI search bots hammering websites without even looking at `robots.txt` (seen this myself), I don't think that adding `robots.txt` support would provide any benefit. Only the AI bot blocking feature of Cloudflare(or similar stuff) might help.

If you agree, then upon merging the #411 you can safely close this PR.

And thank you @cmanley for this PR because it gave me ideas about creating the ViewVC 1.3.0-based Docker container I was talking about in the https://github.com/cmanley/viewvc-docker/issues/7 issue.

**Comment by cmpilato** [comment]
Okay, re-closing this: favicon fixed; relative Location implemented; robots.txt in need of better justification.

**Pull request closed without merging**
