### PR TITLE
Use internal popen.popen instead (master)

### PR DESCRIPTION
**Pull request by futatuki**
This fix issue #141 on master branch, by using internal popen.popen()

### CODE REVIEW

**Comment by cmpilato** [comment]
@futatuki I accepted, but ended up reverting, this pull request merge because I found that the use of popen.popen masks any errors produced during the process.  What we really need is to be able to handle a 'rw' pipe without the blocking issues that can crop up in those types of scenarios.

**Comment by cmpilato** [comment]
(Sorry I couldn't figure out how to cleanly revert and re-open this pull request.)

**Comment by futatuki** [comment]
I see. I'll take a look if bundle popen module can be extended to handle rw pipe for Python < 2.6. If we drop support for Python prior to 2.6, we can use `subprocess.popen` for this purpose.  Anyways I'll make another PR if I can resolve the problem pointed out.

**Comment by futatuki** [comment]
> If we drop support for Python prior to 2.6, we can use `subprocess.popen` for this purpose.

It was incorrect.  class `subprocess.Popen` appeared in Python 2.4.  I'll look over again my code using `subprocess.Popen`.

**Comment by futatuki** [comment]
> I'll make another PR if I can resolve the problem pointed out.

It has transfered to #198.

**Pull request merged**
