### PR TITLE
Use utf8 / utf8_bin consistently across all columns.

### PR DESCRIPTION
**Pull request by ziesemer**
- Contributes to viewvc/viewvc#213.
- Does not yet move to the proposed utf8mb4, but at least brings everything up to consistency with utf8 - and fixes some current production needs.

### CODE REVIEW

**Comment by futatuki** [comment]
Thank you for your contribution.  It is reasonable to make consistency in text fields.

However, for the CVS paths, it seems that `dirs.dir` should keep `binary` type because CVS allows paths which cannot be represented in valid UTF-8 strings, although I can't recall immediately that the code of current ViewVC master can handle those paths correctly or not.

For `branches.branch`, its type should be same as of those fields store tags, so it looks good.

Other changes looks good to me.

**Comment by ziesemer** [comment]
> However, for the CVS paths, it seems that `dirs.dir` should keep `binary` type because CVS allows paths which cannot be represented in valid UTF-8 strings, although I can't recall immediately that the code of current ViewVC master can handle those paths correctly or not.

I'd have to suggest, no, it can't currently handle those paths correctly at present.  Maybe this could be a further improvement along with the proposed move to utf8mb4 - however, for now, the current code is failing with even UTF-8 strings, not even requiring further complexities to fail.  The current state of the pull request fixes this error:

```
Building commit info for revision ###...Traceback (most recent call last):
  File "/usr/local/viewvc-1.3.0-dev/bin/db/svndbadmin", line 399, in <module>
    main(command, repository, revs, verbose, force)
  File "/usr/local/viewvc-1.3.0-dev/bin/db/svndbadmin", line 293, in main
    handle_revision(db, command, repo, rev, verbose)
  File "/usr/local/viewvc-1.3.0-dev/bin/db/svndbadmin", line 255, in handle_revision
    result = db.CheckCommit(commit)
  File "/usr/local/viewvc-1.3.0-dev/lib/cvsdb.py", line 555, in CheckCommit
    dir_id = self.GetDirectoryID(commit.GetDirectory(), 0)
  File "/usr/local/viewvc-1.3.0-dev/lib/cvsdb.py", line 237, in GetDirectoryID
    return self.get_id("dirs", "dir", dir, auto_set)
  File "/usr/local/viewvc-1.3.0-dev/lib/cvsdb.py", line 120, in get_id
    id = self.sql_get_id(table, column, value, auto_set)
  File "/usr/local/viewvc-1.3.0-dev/lib/cvsdb.py", line 97, in sql_get_id
    cursor.execute(sql, sql_args)
  File "/usr/lib/python3.9/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/usr/lib/python3.9/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/usr/lib/python3.9/site-packages/pymysql/connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/lib/python3.9/site-packages/pymysql/connections.py", line 724, in _read_query_result
    result.read()
  File "/usr/lib/python3.9/site-packages/pymysql/connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "/usr/lib/python3.9/site-packages/pymysql/connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "/usr/lib/python3.9/site-packages/pymysql/protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/lib/python3.9/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1267, "Illegal mix of collations (latin1_bin,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '='")
```

Having further traced this, the failing SQL statement is:

```
SELECT id FROM dirs WHERE dir=%s
```

Where the variable is a path that contains characters from the CJK_UNIFIED_IDEOGRAPHS block (U+7###) from Unicode 1.0.1.

**Comment by futatuki** [comment]
>>  However, for the CVS paths, it seems that dirs.dir should keep binary type because CVS allows paths which cannot be represented in valid UTF-8 strings, although I can't recall immediately that the code of current ViewVC master can handle those paths correctly or not.
>
> I'd have to suggest, no, it can't currently handle those paths correctly at present. 

Ah, I'm sorry, in this part, I directed the main part of ViewVC code and I didn't thought about cvsdb.

> Maybe this could be a further improvement along with the proposed move to utf8mb4 - however, for now, the current code is failing with even UTF-8 strings, not even requiring further complexities to fail. 

I suposed paths cannot represented by valid UTF-8 bytes sequences.  It can occure if there exist different encoding between file paths in a CVS repository.
So it cannot be covered by using utf8mb4.

> Having further traced this, the failing SQL statement is:
> 
> ```
> SELECT id FROM dirs WHERE dir=%s
> ```
> 
> Where the variable is a path that contains characters from the CJK_UNIFIED_IDEOGRAPHS block (U+7###) from Unicode 1.0.1.

Thank you for the investigation. 

For binary type columns,  it needs to convert text literal into binary.
e.g. below is not tested yet:
```
diff --git a/lib/cvsdb.py b/lib/cvsdb.py
index e24eccbe..acc776dd 100644
--- a/lib/cvsdb.py
+++ b/lib/cvsdb.py
@@ -90,7 +90,8 @@ class CheckinDatabase:
 
     def sql_get_id(self, table, column, value, auto_set):
         value = reencode(value)
-        sql = "SELECT id FROM %s WHERE %s=%%s" % (table, column)
+        binary_op = "BINARY " if column in ('dir',) else ""
+        sql = "SELECT id FROM %s WHERE %s=%s%%s" % (table, column, binary_op)
         sql_args = (value,)
 
         cursor = self.db.cursor()
@@ -104,7 +105,7 @@ class CheckinDatabase:
             return str(int(id))
 
         # insert the new identifier
-        sql = "INSERT INTO %s(%s) VALUES(%%s)" % (table, column)
+        sql = "INSERT INTO %s(%s) VALUES(%s%%s)" % (table, column, binary_op)
         sql_args = (value,)
         cursor.execute(sql, sql_args)
 
```

**Comment by ziesemer** [comment]
Revised, including your input.  Also, still works with the same use case referenced above, and otherwise not running into any issues yet running database rebuilds against the repositories I'm currently working with.

If `dirs` are binary, should `files` then not be as well?

**Comment by ziesemer** [comment]
I think there needs to be some further considerations here.  I don't think passing `varchar(255) binary` as a column type in the create database script is producing the expected results.  It actually ends up reverting back to the table/database/server-level defaults for character set and collation:

```
show create table dirs \G
*************************** 1. row ***************************
       Table: dirs
Create Table: CREATE TABLE `dirs` (
  `id` mediumint(9) NOT NULL AUTO_INCREMENT,
  `dir` varchar(255) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `dir` (`dir`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci
```

... and then this starts failing again with the repositories I'm currently working with.

Speaking of defaults - <https://dev.mysql.com/doc/refman/8.3/en/charset-server.html> documents the current defaults as being `utf8mb4` (the desired end goal, anyway) and `utf8mb4_0900_ai_ci`.  However, MariaDB (<https://mariadb.com/kb/en/setting-character-sets-and-collations/>) keeps this as `latin1` and `latin1_swedish_ci` - as seen above - and the majority of Linux vendors have entirely replaced MySQL with MariaDB.  I could switch my defaults here, or just keep using my already-modified SQL schema as a one-off - but these approaches don't address the underlying concern.

What you were maybe instead looking for - to match a typical filesystem that only stores bytes as the filename (which are then generally assumed to be UTF-8) - is `VARBINARY` (vs. `VARCHAR`):  <https://dev.mysql.com/doc/refman/8.3/en/binary-varbinary.html>.

However, this will significantly impact the ability to search the database / use the "commit query" feature - which I understand is pretty much the entire reason the commit database exists.  Using binary column types here will prevent the use of any regular expression operators within MySQL.  Per <https://dev.mysql.com/doc/refman/8.0/en/regexp.html>:

> Prior to MySQL 8.0.22, it was possible to use binary string arguments with these functions, but they yielded inconsistent results. In MySQL 8.0.22 and later, use of a binary string with any of the MySQL regular expression functions is rejected with [ER_CHARACTER_SET_MISMATCH](https://dev.mysql.com/doc/mysql-errors/8.0/en/server-error-reference.html#error_er_character_set_mismatch).

(This notice is further refined in the 8.3 version of the docs at <https://dev.mysql.com/doc/refman/8.3/en/regexp.html>, but the restriction remains the same.)

I'm not the expert here, but I believe Subversion itself is currently limited to UTF-8.  From <https://svn.apache.org/repos/asf/subversion/trunk/notes/unicode-composition-for-filenames>:

> UTF-8, the internal Unicode encoding of choice for Subversion, encodes codepoints in (a series of) bytes (octets).

I'm not sure if I'm taking this out of context at all, and if Subversion is, in-fact, already handing "binary", non-Unicode characters in filenames and paths.  However, even if Subversion itself does, I'm seeing many other libraries that are typically used directly alongside SVN that don't.

To set the stage here, to the best of my understanding, this database is only to provide for the "commit query" / search capabilities.  This isn't even something that has the potential to cause data loss in the future.  The current capabilities don't even support UTF-8.  This can be fixed, and then continue to be improved upon over time.

## I propose:

1. Using a roll-back to my prior commit, to use UTF-8 consistently across all fields, including `dirs` and `files`.  This will meet the immediate needs of myself and others.  Allow that to complete this pull request.
2. If a move to `utf8mb4` is the agreed upon direction (it makes sense to me) - that can be included as a follow-up revision, and I can even submit as a follow-on pull request.  This will support all Unicode planes (not just the Basic Multilingual Plane / BMP), and further reduce the likelihood that any repositories run into a limitation here,
3. Before use-cases beyond `utf8mb4` be considered, I think the more likely limitations are the 255-character limits on the `dirs` and `files` (especially the `dirs`).  Even in most version of Windows, there are potential gaps between the current 255-character limits and 257/259/260 characters.  Even the Python installer on Windows now provides a one-click option to "Disable path length limit" ("MAX_PATH") during installation.
4. If a true-binary form of `dirs` and `files` must be kept, maybe store them in additional columns along-side the existing `dir` and `file` columns - allowing for both the current search capabilities (including regular expressions), while also allowing for access to the direct binary form, if/when needed?

**Comment by futatuki** [comment]
I agree 1. and 2.

For 3., in very old CVS repositories, I actually saw sometimes mixture of encodings within a CVS repository (but they were not ViewVC/ViewCVS). Perhaps in those case, they could be covered by the default latin1 character set, regardlessly actual character set/encodings. 

For 4, if `dirs.dir` and `files.file` store values in text form,  we can store those paths which cannot be represented by valid UTF-8 bytes sequences as "backslashreplace" form or some other cooked form.  In the case I cannot imagine the use case that needs truely binary form of the paths.

Anyways, I agree that conceptually this can be merged for going ahead.

**Comment by cmpilato** [comment]
@futatuki FWIW, I'm deferring to your expertise here.  If you're okay with state of things and want to merge, go for it!

**Comment by futatuki** [comment]
@ziesemer sorry for delay.
@cmpilato thank you for the encouragement.
Now I could confirm the change, I merged this. Thank you.

**Comment by futatuki** [comment]
Note:
> For 4, if dirs.dir and files.file store values in text form, we can store those paths which cannot be represented by valid UTF-8 bytes sequences as "backslashreplace" form or some other cooked form.

This is already done by cvsdb._reencode().

**Pull request merged**
