### PR TITLE
Rework custom popen() as a wrapper around subprocess.Popen()

### PR DESCRIPTION
**Pull request by cmpilato**
ViewVC's custom popen module was written some 20 years ago to avoid the security pitfalls of using `os.system()` or `os.popen()` (which accept shell-like command strings that require special escaping and careful handling.  But `os.popen()` has long since been replaced with `subprocess.Popen()`, and the more custom code we can lose from ViewVC, the easier it is to maintain.

### CODE REVIEW

**Comment by cmpilato** [comment]
This all started when I noticed a few things about the existing code:

  * we never opened a write pipe (so all the popen code that allowed that was dead)
  * we had a decently sized chunk of code written just to allow some debugging of child processes (so, effectively dead code)

I don't really have a way to test on Windows at the moment, and I've never used the subprocess module myself before, but ... this seems like a great place to ditch custom code, and I _think_ means that Windows users don't need the Python for Windows extensions any more.  Maybe?

**Comment by cmpilato** [comment]
@futatuki Any thoughts on this?

**Comment by futatuki** [comment]
I also don't have ViewVC test environment on Windows yet (because I don't success to build Subversion on Windows), however I believe that the `subprocess` module is good enough to communicate and/or to handle child process (E.g. test codes for Subversion command line utility and SWIG Python bindings use it.),  and I think there is few reason to keep old popen interface. 

I've already replaced custom `popen` with `subprocess.popen` on branches for support Python 3, and threre is only one place still using popen.popen, to get version of `cvsnt` utility in bin/standalone.py.

So I think we can drop popen.py itself.

**Comment by futatuki** [comment]
This will be merged indirectly by merging python3-support branch to master.

**Pull request closed without merging**
