### PR TITLE
Unify method to convert property values and meta data from bytes to str

### PR DESCRIPTION
**Pull request by futatuki**
The function _to_str() assumes one to one correspondence between bytes
and str for paths and URLs, and not for user visible text. So we use
_normalize_property_value() for this purpose to convert Subversion
meta data like special property svn:author and svn:log.

* lib/vclib/svn/svn_repos.py
 (_normalize_property_value):
  - Explicitly specifiy 'strict' handler in first try to decode.
  - Add optional parameter 'errors' to use with encoding_hint for fallback
 
  (_normalize_property): Add optional parameter 'errors' for property value.
  (_split_revprops): Make sure to return msg and author as "user visible"
   str text, with 'backslashreplace' errors handler
  (LocalSubversionRepository.dirlogs, LocalSubversionRepository.itemlog):
   Use _normalize_property to convert lockinfo.
  (LocalSubversionRepository._revinfo_helper): Remove check for msg and author,
  which assured to be str or None by _split_revprops.

### CODE REVIEW

**Comment by cmpilato** [comment]
I wasn't originally settled on how to handle log messages and authors that weren't valid UTF-8 inside Subversion.  I have, for example, a test repository that's got a log message whose value is PNG image data.  But it's easy to argue that those who similarly misuse their version control system deserve whatever ugliness results from it.  (All that to say I'm okay with this metadata being forced to produce *something* visible.)

I do have a larger question, though, and that's about the various different "errors" fallbacks you're introducing.  Is there a method to the madness?  Why do we use one style in some places but another style elsewhere.  For example, https://docs.python.org/3/library/codecs.html#codecs.xmlcharrefreplace_errors leads me to believe that the `xmlcharrefreplace` style is for *encoding* only, yet we're using it with `.decode()`.  Can you help me understand your vision here?

**Comment by futatuki** [comment]
Using 'xmlcharefreplace' was my mistakes. I think there are three type of context to decode bytes in ViewVC

1.  One to one correspondcy between `bytes` expression and `str `expression is needed.
I assume paths are applicable. This should be valid utf-8 / Unicode.  So I use `'surrogateescape'` to convert them for irregular data (as foolproof). It may need to reencode as user visible text to display and as URL encoded sequence for links.  I thought this contains property names but ViewVC has already code to discard if invalid property names are found,
so I think property names are later case 2.  I use vclib.svn.svn_repos._to_str() for this purpose.

2.  For user visible texts.
I assume text meta data like author, log message, and lock owner.  I suppose authors and/or log messages are some other charset/encoding than Unicode/utf-8, but I didn't suppose log messages are some binary content, though.  For user visible text, the candidate of error handler are `'ignore'`, `'replace'`, and `'backslashreplace'`.  I prefer `'backslashreplace'` because user may be able to reconstruct "right" text from corrupt text converted with this handler (For my misunderstanding, I used 'xmlcharrefreplace' for it).  I use vclib.svn.svn_repos._normalize_property_value() for this purpose. (For viewvc.py, simular function may need, but look over after I decided how to handle them).  Also, I don't have confidence which is better to precede 'utf-8' or encoding hint.

3.  Some text otherwise binary data, expected to fail to convert if it contains invalid sequence.
I assume file contents and property values other than 2. case.  To detect failure in conversion,
I use `'strict'` error handler (this is default handler, but I explicitly used).

**Comment by futatuki** [comment]
Also, It is need to look over vclib/ccvs/* for decode encode usage, (but it is another issue).

**Comment by futatuki** [comment]
I think this PR is a bit out of dated, and it is better to withdraw for reconsider.

**Pull request closed without merging**
