### PR TITLE
issue #277: Convert some paths to strings before splitting into parts

### PR DESCRIPTION
**Pull request by cmpilato**

### CODE REVIEW

**Comment by futatuki** [comment]
It looks good for me.  This fix assumes that the parameter PATH_PARTS in GenericViewVCAuthorizer.check_path_access() should be a list of path parts in str type, and it is reasonable because we decided that we treat paths as str except in vclib.

**Review by futatuki — APPROVED** [review]

**Comment by futatuki** [comment]
It seems there still exists bytes/str mixture in [line 786 in svn_repos.py](https://github.com/viewvc/viewvc/blob/bab50efc25010ce3e4c9064120a55a3e915c45f1/lib/vclib/svn/svn_repos.py#L796), but it seem it is not related to the issue #277.

**Comment by cmpilato** [comment]
@futatuki How hard do you think it would be to get ViewVC under type-checking (with `mypy`, etc.)?  Every time I try to read the Subversion code, I find myself having to re-establish my bearings around what's a `str` and what's `bytes` ... it's a bit infuriating.

**Comment by cmpilato** [comment]
> It seems there still exists bytes/str mixture in [line 786 in svn_repos.py](https://github.com/viewvc/viewvc/blob/bab50efc25010ce3e4c9064120a55a3e915c45f1/lib/vclib/svn/svn_repos.py#L796), but it seem it is not related to the issue #277.

Good catch.  I've fixed that, too, I think.

**Comment by futatuki** [comment]
> @futatuki How hard do you think it would be to get ViewVC under type-checking (with `mypy`, etc.)? Every time I try to read the Subversion code, I find myself having to re-establish my bearings around what's a `str` and what's `bytes` ... it's a bit infuriating.

To accomplish it,  we have to wrap Subversion Python bindings modules to annotate types they use, and not to use bare bindings functions.  Because functions in Python bindings modules generated by SWIG have annotations not for type checking but for programmers to know correspondence of function parameters between C API and wrapper functions.

Also, if we introduce a new layer to wrap them,  it is better to re-construct return values of their function to use str for the components we want to treat as it is, like paths.  Most of confusion between bytes/str in ViewVC come from bare functions in Subversion bindings modules,  which is only a thin wrapper of C API and never use str as return values and their components.

**Pull request merged**
